apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: centos7
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: centos7
spec:
  type: NodePort  # Cambia el tipo a NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: httpd