name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Ajusta esto según tu flujo de trabajo de desarrollo
    paths:
      - 'ymal/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubernetes context
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
        kubectl version  # Esto es para verificar que kubectl está configurado correctamente

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./ymal/  # Asegúrate de que tus manifiestos están en el directorio `ymal/`

    - name: Clean up deleted Kubernetes resources
      run: |
        git fetch origin ${{ github.event.before }}
        git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.sha }} -- ymal/ > deleted_files.txt
        cat deleted_files.txt | while read file; do
          git show ${{ github.event.before }}:$file > temp.yaml  # Recupera el archivo del estado anterior
          kubectl delete -f temp.yaml --ignore-not-found  # Usa el archivo temporal para eliminar el recurso
          rm temp.yaml  # Elimina el archivo temporal
        done
